services:
  # Backend Node/Express Web Service
  - type: web
    name: bajaj-api-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: MONGO_URI
        sync: true
      - key: PORT
        value: 5000

  # Frontend React/Vite Web Service
  - type: web
    name: bajaj-api-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: VITE_API_URL
        fromService:
          name: bajaj-api-backend
          value: url
